# Generated by Django 5.2.12 on 2026-03-08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DMConversation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("GROUP", "Group")],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="dm_avatars/")),
                (
                    "direct_key",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dm_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="DMMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ciphertext", models.TextField(blank=True, null=True)),
                ("nonce", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "encryption_version",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("sender_key_id", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="dm.dmconversation",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_dm_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "uuid"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at", "uuid"],
                        name="dm_msg_conv_created_uuid_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DMMessageReaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="dm.dmmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["message", "emoji"], name="dm_react_msg_emoji_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "emoji"),
                        name="dm_react_unique_message_user_emoji",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DMConversationParticipant",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_participants",
                        to="dm.dmconversation",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_by_participants",
                        to="dm.dmmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "conversation"], name="dm_part_user_conv_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "user"),
                        name="dm_participant_unique_conversation_user",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="dmconversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="dm_conversations",
                through="dm.DMConversationParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
