# Generated by Django 5.2.12 on 2026-03-04 00:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("tag", models.CharField(editable=False, max_length=4)),
                ("custom_status", models.CharField(blank=True, max_length=100)),
                ("theme_color", models.CharField(default="#508991", max_length=7)),
                ("is_online", models.BooleanField(default=False)),
            ],
        ),
    ]
